[config]
model="GPT-5-pro"
fallback_models = ["gemini-2.5-pro", "gpt-5"]

[pr_description]
enable_pr_diagram = true
enable_help_text = true
enable_large_pr_handling = true
generate_ai_title = true
extra_instructions = ""

[pr_compliance]
enable_todo_scan = true
enable_help_text = true
enable_ticket_labels = true
enable_no_ticket_labels = true
check_pr_additional_content = true

[pr_code_suggestions]
enable_help_text = true
demand_code_suggestions_self_review = true
# # Recipe for maximum suggestion comprehensiveness
# suggestions_depth = "exhaustive"
# enable_suggestion_type_reuse = true
# num_code_suggestions_per_chunk = 100
# num_best_practice_suggestions = 100

[github_app]
pr_commands = [
    "/describe",
    "/compliance",
    "/improve",
    '/ask "Perform a review as a Security Expert. Include sections for Warnings, Improvements and Best Practices. Additionally, create a Threat Model based on the STRIDE framework for this PR."'
]

[gitlab]
pr_commands = [
    "/describe",
    "/compliance",
    "/improve",
    '/ask "Perform a review as a Security Expert. Include sections for Warnings, Improvements and Best Practices. Additionally, create a Threat Model based on the STRIDE framework for this PR."'
]

[bitbucket_app]
pr_commands = [
    "/describe",
    "/compliance",
    "/improve",
    '/ask "Perform a review as a Security Expert. Include sections for Warnings, Improvements and Best Practices. Additionally, create a Threat Model based on the STRIDE framework for this PR."'
]
