[config]
model="gemini-2.5-pro"
fallback_models = ["gpt-4.1"]

[github_app]
pr_commands = [
    "/describe",
    "/review",
    "/improve",
    "/analyze",
    "/checks",
    "/describe",
]

[pr_description]
add_diagram = true
enable_help_text = true
enable_large_pr_handling = true
generate_ai_title = true

[pr_reviewer]
enable_help_text = true
num_max_findings = 10
require_score_review = true
require_can_be_split_review = true
enable_review_labels_security = true

[pr_code_suggestions]
enable_help_text = true